# Profil PROD — ne contient que ce qui diffère de application.yml (base commune).

spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 60
