server.port: 9001
spring:
  application.name: Komflow

  # ===============================
  # = DATA SOURCE
  # ===============================
  # Set here configurations for the database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/komflow
    username: komflow_user
    password: komflow_user

  sql:
    init.mode: always
    init.schema-locations: classpath:db/migration/schema.sql

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.default_schema: komflow

  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:db/migration
    out-of-order: false
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/komflow
    default-schema: komflow
    user: komflow_user
    password: komflow_user


# Configuration JWT
jwt:
  secret-key: "${JWT_SECRET:de717372299e516520195b110c787d30b004db006a9692498bb04914556eca1f}"
  expiration-ms: "${JWT_EXPIRATION_MS:3600000}"
  issuer: "${JWT_ISSUER:komflow-app}"

logging:
  level:
    org.springframework.security: DEBUG
