# Server Configuration
server:
  port: ${SERVER_PORT:9001}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${APP_NAME:Komflow}

  # ===============================
  # = DATA SOURCE
  # ===============================
  # Set here configurations for the database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:komflow}
    username: ${DB_USERNAME:komflow_user}
    password: ${DB_PASSWORD:komflow_user}

  sql:
    init.mode: always
    init.schema-locations: classpath:db/migration/schema.sql

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.default_schema: ${DB_SCHEMA:komflow}

  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:db/migration
    out-of-order: false
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:komflow}
    default-schema: ${DB_SCHEMA:komflow}
    user: ${DB_USERNAME:komflow_user}
    password: ${DB_PASSWORD:komflow_user}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:gilleskemgoum@gmail.com}
    password: ${MAIL_PASSWORD:xvahdlfnnqzpgeva}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

# Swagger
springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}

# Configuration JWT
jwt:
  secret-key: "${JWT_SECRET:de717372299e516520195b110c787d30b004db006a9692498bb04914556eca1f}"
  expiration-ms: ${JWT_EXPIRATION_MS:43200000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
  issuer: ${JWT_ISSUER:komflow-app}
  # Durée d'expiration du token d'accès en secondes (2 heures = 7200 secondes)
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.kompozith.komflow.features.auth.CustomUserDetailsService: DEBUG
