CREATE SEQUENCE IF NOT EXISTS aut_audit_logs_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS aut_roles_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS cnt_contacts_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS cnt_tags_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS core_file_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS msg_campaign_contact_results_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS msg_campaigns_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS msg_event_registration_workflow_steps_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS msg_events_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS msg_messages_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS org_members_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS org_organizations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS prs_persons_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS prs_phone_number_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS prs_users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE aut_audit_logs
(
    id                BIGINT       NOT NULL,
    action            VARCHAR(255) NOT NULL,
    object_type       VARCHAR(255) NOT NULL,
    object_id         VARCHAR(255) NOT NULL,
    connected_user_id VARCHAR(255),
    ip_address        VARCHAR(255),
    user_agent        VARCHAR(255),
    user_location     VARCHAR(255),
    details           VARCHAR(255),
    channel           VARCHAR(255),
    date              TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_aut_audit_logs PRIMARY KEY (id)
);

CREATE TABLE aut_role_permissions
(
    aut_role_id         BIGINT NOT NULL,
    aut_permission_code VARCHAR(255)
);

CREATE TABLE aut_roles
(
    id          BIGINT       NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    type        VARCHAR(255) DEFAULT 'CUSTOM',
    active      BOOLEAN      DEFAULT TRUE,
    CONSTRAINT pk_aut_roles PRIMARY KEY (id)
);

CREATE TABLE bil_plans
(
    code                    VARCHAR(50)  NOT NULL,
    label                   VARCHAR(100) NOT NULL,
    price_monthly_cts_cents BIGINT       NOT NULL,
    max_contacts_total      INTEGER      NOT NULL,
    max_campaigns_per_month INTEGER      NOT NULL,
    max_emails_per_month    INTEGER      NOT NULL,
    max_sms_per_month       INTEGER      NOT NULL,
    max_whatsapp_per_month  INTEGER      NOT NULL,
    max_users_per_org       INTEGER      NOT NULL,
    can_use_whatsapp        BOOLEAN      NOT NULL,
    can_use_sms             BOOLEAN      NOT NULL,
    can_use_workflows       BOOLEAN      NOT NULL,
    can_use_advanced_rbac   BOOLEAN      NOT NULL,
    CONSTRAINT pk_bil_plans PRIMARY KEY (code)
);

CREATE TABLE bil_subscriptions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id    BIGINT                                  NOT NULL,
    plan_code          VARCHAR(50)                             NOT NULL,
    status             VARCHAR(30)                             NOT NULL,
    current_period_end TIMESTAMP WITHOUT TIME ZONE,
    external_id        VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_bil_subscriptions PRIMARY KEY (id)
);

CREATE TABLE bil_usage_counters
(
    organization_id BIGINT      NOT NULL,
    metric          VARCHAR(50) NOT NULL,
    year_month      VARCHAR(6)  NOT NULL,
    count           BIGINT      NOT NULL,
    CONSTRAINT pk_bil_usage_counters PRIMARY KEY (organization_id, metric, year_month)
);

CREATE TABLE cnt_contact_tags
(
    cnt_contact_id BIGINT NOT NULL,
    cnt_tag_id     BIGINT NOT NULL,
    CONSTRAINT pk_cnt_contact_tags PRIMARY KEY (cnt_contact_id, cnt_tag_id)
);

CREATE TABLE cnt_contacts
(
    id                       BIGINT  NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255),
    enabled                  BOOLEAN NOT NULL,
    last_message_received_at TIMESTAMP WITHOUT TIME ZONE,
    civility                 VARCHAR(255),
    profession               VARCHAR(255),
    age_range                VARCHAR(255),
    objectives               TEXT,
    website_url              VARCHAR(255),
    prs_person_id            BIGINT  NOT NULL,
    organization_id          BIGINT  NOT NULL,
    CONSTRAINT pk_cnt_contacts PRIMARY KEY (id)
);

CREATE TABLE cnt_tags
(
    id              BIGINT       NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    name            VARCHAR(255) NOT NULL,
    color_code      VARCHAR(255) NOT NULL,
    description     VARCHAR(255),
    enabled         BOOLEAN      NOT NULL,
    organization_id BIGINT       NOT NULL,
    CONSTRAINT pk_cnt_tags PRIMARY KEY (id)
);

CREATE TABLE core_file
(
    id              BIGINT       NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    name            VARCHAR(255) NOT NULL,
    url             VARCHAR(255) NOT NULL,
    organization_id BIGINT       NOT NULL,
    CONSTRAINT pk_core_file PRIMARY KEY (id)
);

CREATE TABLE msg_campaign_cc_tags
(
    cnt_tag_id      BIGINT NOT NULL,
    msg_campaign_id BIGINT NOT NULL
);

CREATE TABLE msg_campaign_cci_tags
(
    cnt_tag_id      BIGINT NOT NULL,
    msg_campaign_id BIGINT NOT NULL
);

CREATE TABLE msg_campaign_contact_results
(
    id            BIGINT      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    campaign_id   BIGINT      NOT NULL,
    contact_id    BIGINT      NOT NULL,
    channel       VARCHAR(20) NOT NULL,
    status        VARCHAR(10) NOT NULL,
    error_message TEXT,
    CONSTRAINT pk_msg_campaign_contact_results PRIMARY KEY (id)
);

CREATE TABLE msg_campaigns
(
    id              BIGINT       NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    name            VARCHAR(255),
    description     VARCHAR(255),
    message_id      BIGINT,
    status          VARCHAR(255) NOT NULL,
    scheduled_at    TIMESTAMP WITHOUT TIME ZONE,
    organization_id BIGINT       NOT NULL,
    CONSTRAINT pk_msg_campaigns PRIMARY KEY (id)
);

CREATE TABLE msg_campaigns_contacts
(
    campaign_id BIGINT NOT NULL,
    contacts_id BIGINT NOT NULL
);

CREATE TABLE msg_campaigns_tags
(
    contacts_id BIGINT NOT NULL,
    tags_id     BIGINT NOT NULL
);

CREATE TABLE msg_email_cc_contacts
(
    cnt_contact_id  BIGINT NOT NULL,
    msg_campaign_id BIGINT NOT NULL
);

CREATE TABLE msg_email_cci_contacts
(
    cnt_contact_id  BIGINT NOT NULL,
    msg_campaign_id BIGINT NOT NULL
);

CREATE TABLE msg_event_registration_workflow_steps
(
    id               BIGINT      NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    msg_event_id     BIGINT      NOT NULL,
    msg_message_id   BIGINT,
    step_type        VARCHAR(30) NOT NULL,
    recipient_type   VARCHAR(30) NOT NULL,
    delay_minutes    INTEGER,
    condition_type   VARCHAR(40),
    condition_value  VARCHAR(255),
    position         INTEGER     NOT NULL,
    enabled          BOOLEAN     NOT NULL,
    recipient_emails TEXT,
    CONSTRAINT pk_msg_event_registration_workflow_steps PRIMARY KEY (id)
);

CREATE TABLE msg_events
(
    id               BIGINT       NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    title            VARCHAR(200) NOT NULL,
    slug             VARCHAR(220),
    description      TEXT,
    location         VARCHAR(255),
    subtitle         VARCHAR(255),
    address          VARCHAR(255),
    event_mode       VARCHAR(20),
    meeting_url      VARCHAR(1024),
    banner_image_url VARCHAR(2048),
    highlights       TEXT,
    agenda           TEXT,
    start_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_at           TIMESTAMP WITHOUT TIME ZONE,
    timezone         VARCHAR(100),
    organization_id  BIGINT       NOT NULL,
    CONSTRAINT pk_msg_events PRIMARY KEY (id)
);

CREATE TABLE msg_message_attachments
(
    core_file_id   BIGINT NOT NULL,
    msg_message_id BIGINT NOT NULL
);

CREATE TABLE msg_message_events
(
    msg_event_id   BIGINT NOT NULL,
    msg_message_id BIGINT NOT NULL
);

CREATE TABLE msg_messages
(
    id              BIGINT       NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    title           VARCHAR(255),
    content         TEXT         NOT NULL,
    channel         VARCHAR(255) NOT NULL,
    organization_id BIGINT       NOT NULL,
    CONSTRAINT pk_msg_messages PRIMARY KEY (id)
);

CREATE TABLE org_member_permissions
(
    member_id  BIGINT NOT NULL,
    permission VARCHAR(100)
);

CREATE TABLE org_members
(
    id                      BIGINT      NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255),
    organization_id         BIGINT      NOT NULL,
    user_id                 BIGINT      NOT NULL,
    role                    VARCHAR(20) NOT NULL,
    status                  VARCHAR(20) NOT NULL,
    invited_email           VARCHAR(255),
    invite_token            VARCHAR(64),
    invite_token_expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_org_members PRIMARY KEY (id)
);

CREATE TABLE org_organizations
(
    id            BIGINT       NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255) NOT NULL,
    slug          VARCHAR(100) NOT NULL,
    plan_code     VARCHAR(50)  NOT NULL,
    active        BOOLEAN      NOT NULL,
    trial_ends_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_org_organizations PRIMARY KEY (id)
);

CREATE TABLE prs_persons
(
    id         BIGINT       NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    email      VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    language   VARCHAR(255),
    country    VARCHAR(255),
    city       VARCHAR(255),
    timezone   VARCHAR(255),
    user_id    BIGINT,
    CONSTRAINT pk_prs_persons PRIMARY KEY (id)
);

CREATE TABLE prs_phone_number
(
    id                BIGINT NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    number            VARCHAR(255),
    is_whatsap_number VARCHAR(255),
    person_id         BIGINT,
    contact_id        BIGINT,
    CONSTRAINT pk_prs_phone_number PRIMARY KEY (id)
);

CREATE TABLE prs_user_roles
(
    aut_role_id BIGINT NOT NULL,
    prs_user_id BIGINT NOT NULL,
    CONSTRAINT pk_prs_user_roles PRIMARY KEY (aut_role_id, prs_user_id)
);

CREATE TABLE prs_users
(
    id            BIGINT       NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    username      VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    prs_person_id BIGINT       NOT NULL,
    CONSTRAINT pk_prs_users PRIMARY KEY (id)
);

CREATE TABLE prs_users_logs
(
    user_id BIGINT NOT NULL,
    logs_id BIGINT NOT NULL
);

CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    token       VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

ALTER TABLE bil_usage_counters
    ADD CONSTRAINT uc_830b01f41407eebc0d0a5f200 UNIQUE (organization_id, metric, year_month);

ALTER TABLE aut_roles
    ADD CONSTRAINT uc_aut_roles_name UNIQUE (name);

ALTER TABLE bil_subscriptions
    ADD CONSTRAINT uc_bil_subscriptions_organization UNIQUE (organization_id);

ALTER TABLE cnt_contacts
    ADD CONSTRAINT uc_cnt_contacts_prs_person UNIQUE (prs_person_id);

ALTER TABLE cnt_tags
    ADD CONSTRAINT uc_cnt_tags_name UNIQUE (name);

ALTER TABLE org_members
    ADD CONSTRAINT uc_d1c132e9c034c594422766d19 UNIQUE (organization_id, user_id);

ALTER TABLE msg_message_attachments
    ADD CONSTRAINT uc_msg_message_attachments_core_file UNIQUE (core_file_id);

ALTER TABLE org_members
    ADD CONSTRAINT uc_org_members_invite_token UNIQUE (invite_token);

ALTER TABLE org_organizations
    ADD CONSTRAINT uc_org_organizations_slug UNIQUE (slug);

ALTER TABLE prs_users_logs
    ADD CONSTRAINT uc_prs_users_logs_logs UNIQUE (logs_id);

ALTER TABLE prs_users
    ADD CONSTRAINT uc_prs_users_prs_person UNIQUE (prs_person_id);

ALTER TABLE prs_users
    ADD CONSTRAINT uc_prs_users_username UNIQUE (username);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

CREATE INDEX idx_ccr_campaign_id_status ON msg_campaign_contact_results (campaign_id, status);

ALTER TABLE bil_subscriptions
    ADD CONSTRAINT FK_BIL_SUBSCRIPTIONS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES org_organizations (id);

ALTER TABLE cnt_contacts
    ADD CONSTRAINT FK_CNT_CONTACTS_ON_PRS_PERSON FOREIGN KEY (prs_person_id) REFERENCES prs_persons (id);

ALTER TABLE msg_campaigns
    ADD CONSTRAINT FK_MSG_CAMPAIGNS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES msg_messages (id);

ALTER TABLE msg_campaign_contact_results
    ADD CONSTRAINT FK_MSG_CAMPAIGN_CONTACT_RESULTS_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES msg_campaigns (id);

CREATE INDEX idx_ccr_campaign_id ON msg_campaign_contact_results (campaign_id);

ALTER TABLE msg_campaign_contact_results
    ADD CONSTRAINT FK_MSG_CAMPAIGN_CONTACT_RESULTS_ON_CONTACT FOREIGN KEY (contact_id) REFERENCES cnt_contacts (id);

ALTER TABLE msg_event_registration_workflow_steps
    ADD CONSTRAINT FK_MSG_EVENT_REGISTRATION_WORKFLOW_STEPS_ON_MSG_EVENT FOREIGN KEY (msg_event_id) REFERENCES msg_events (id);

ALTER TABLE msg_event_registration_workflow_steps
    ADD CONSTRAINT FK_MSG_EVENT_REGISTRATION_WORKFLOW_STEPS_ON_MSG_MESSAGE FOREIGN KEY (msg_message_id) REFERENCES msg_messages (id);

ALTER TABLE org_members
    ADD CONSTRAINT FK_ORG_MEMBERS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES org_organizations (id);

ALTER TABLE org_members
    ADD CONSTRAINT FK_ORG_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES prs_users (id);

ALTER TABLE prs_persons
    ADD CONSTRAINT FK_PRS_PERSONS_ON_USER FOREIGN KEY (user_id) REFERENCES prs_users (id);

ALTER TABLE prs_phone_number
    ADD CONSTRAINT FK_PRS_PHONE_NUMBER_ON_CONTACT FOREIGN KEY (contact_id) REFERENCES cnt_contacts (id);

ALTER TABLE prs_phone_number
    ADD CONSTRAINT FK_PRS_PHONE_NUMBER_ON_PERSON FOREIGN KEY (person_id) REFERENCES prs_persons (id);

ALTER TABLE prs_users
    ADD CONSTRAINT FK_PRS_USERS_ON_PRS_PERSON FOREIGN KEY (prs_person_id) REFERENCES prs_persons (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES prs_users (id);

ALTER TABLE aut_role_permissions
    ADD CONSTRAINT fk_aut_role_permissions_on_role FOREIGN KEY (aut_role_id) REFERENCES aut_roles (id);

ALTER TABLE cnt_contact_tags
    ADD CONSTRAINT fk_cntcontag_on_contact FOREIGN KEY (cnt_contact_id) REFERENCES cnt_contacts (id);

ALTER TABLE cnt_contact_tags
    ADD CONSTRAINT fk_cntcontag_on_tag FOREIGN KEY (cnt_tag_id) REFERENCES cnt_tags (id);

ALTER TABLE msg_campaign_cci_tags
    ADD CONSTRAINT fk_msgcamccitag_on_campaign FOREIGN KEY (msg_campaign_id) REFERENCES msg_campaigns (id);

ALTER TABLE msg_campaign_cci_tags
    ADD CONSTRAINT fk_msgcamccitag_on_tag FOREIGN KEY (cnt_tag_id) REFERENCES cnt_tags (id);

ALTER TABLE msg_campaign_cc_tags
    ADD CONSTRAINT fk_msgcamcctag_on_campaign FOREIGN KEY (msg_campaign_id) REFERENCES msg_campaigns (id);

ALTER TABLE msg_campaign_cc_tags
    ADD CONSTRAINT fk_msgcamcctag_on_tag FOREIGN KEY (cnt_tag_id) REFERENCES cnt_tags (id);

ALTER TABLE msg_campaigns_contacts
    ADD CONSTRAINT fk_msgcamcon_on_campaign FOREIGN KEY (campaign_id) REFERENCES msg_campaigns (id);

ALTER TABLE msg_campaigns_contacts
    ADD CONSTRAINT fk_msgcamcon_on_contact FOREIGN KEY (contacts_id) REFERENCES cnt_contacts (id);

ALTER TABLE msg_campaigns_tags
    ADD CONSTRAINT fk_msgcamtag_on_campaign FOREIGN KEY (contacts_id) REFERENCES msg_campaigns (id);

ALTER TABLE msg_campaigns_tags
    ADD CONSTRAINT fk_msgcamtag_on_tag FOREIGN KEY (tags_id) REFERENCES cnt_tags (id);

ALTER TABLE msg_email_cc_contacts
    ADD CONSTRAINT fk_msgemacccon_on_campaign FOREIGN KEY (msg_campaign_id) REFERENCES msg_campaigns (id);

ALTER TABLE msg_email_cc_contacts
    ADD CONSTRAINT fk_msgemacccon_on_contact FOREIGN KEY (cnt_contact_id) REFERENCES cnt_contacts (id);

ALTER TABLE msg_email_cci_contacts
    ADD CONSTRAINT fk_msgemaccicon_on_campaign FOREIGN KEY (msg_campaign_id) REFERENCES msg_campaigns (id);

ALTER TABLE msg_email_cci_contacts
    ADD CONSTRAINT fk_msgemaccicon_on_contact FOREIGN KEY (cnt_contact_id) REFERENCES cnt_contacts (id);

ALTER TABLE msg_message_attachments
    ADD CONSTRAINT fk_msgmesatt_on_file FOREIGN KEY (core_file_id) REFERENCES core_file (id);

ALTER TABLE msg_message_attachments
    ADD CONSTRAINT fk_msgmesatt_on_message FOREIGN KEY (msg_message_id) REFERENCES msg_messages (id);

ALTER TABLE msg_message_events
    ADD CONSTRAINT fk_msgmeseve_on_event FOREIGN KEY (msg_event_id) REFERENCES msg_events (id);

ALTER TABLE msg_message_events
    ADD CONSTRAINT fk_msgmeseve_on_message FOREIGN KEY (msg_message_id) REFERENCES msg_messages (id);

ALTER TABLE org_member_permissions
    ADD CONSTRAINT fk_org_member_permissions_on_organization_member FOREIGN KEY (member_id) REFERENCES org_members (id);

ALTER TABLE prs_users_logs
    ADD CONSTRAINT fk_prsuselog_on_audit_log FOREIGN KEY (logs_id) REFERENCES aut_audit_logs (id);

ALTER TABLE prs_users_logs
    ADD CONSTRAINT fk_prsuselog_on_user FOREIGN KEY (user_id) REFERENCES prs_users (id);

ALTER TABLE prs_user_roles
    ADD CONSTRAINT fk_prsuserol_on_role FOREIGN KEY (aut_role_id) REFERENCES aut_roles (id);

ALTER TABLE prs_user_roles
    ADD CONSTRAINT fk_prsuserol_on_user FOREIGN KEY (prs_user_id) REFERENCES prs_users (id);

CREATE TABLE komflow.auth_password_reset_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    otp_code    VARCHAR(6)                              NOT NULL,
    reset_token VARCHAR(64),
    used        BOOLEAN                                 NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_auth_password_reset_tokens PRIMARY KEY (id)
);

ALTER TABLE komflow.auth_password_reset_tokens
    ADD CONSTRAINT uc_auth_password_reset_tokens_reset_token UNIQUE (reset_token);

ALTER TABLE komflow.auth_password_reset_tokens
    ADD CONSTRAINT FK_AUTH_PASSWORD_RESET_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES prs_users (id);